### ISSUE TITLE
Error when creating new blog from template

### ISSUE THREAD

**Issue by jeffro84** [wpmudev/blogtemplates#3]
When I create a new blog from a template, I get the following error:

Insertion Error: Table 'frobrowe_wp263.wpms_9_wc_download_log' doesn't exist - The template was not applied. (New Blog Templates - With CREATE TABLE query for Additional Tables)

The site still gets created, but not everything is copied over.  If you look at the WooCommerce status page, there are some tables that are missing:

wpms_9_woocommerce_sessions |   | Table does not exist
wpms_9_woocommerce_api_keys |   | Table does not exist
wpms_9_woocommerce_attribute_taxonomies |   | Table does not exist
wpms_9_woocommerce_downloadable_product_permissions |   | Table does not exist
wpms_9_woocommerce_order_items |   | Table does not exist
wpms_9_woocommerce_order_itemmeta |   | Table does not exist
wpms_9_woocommerce_tax_rates |   | Table does not exist
wpms_9_woocommerce_tax_rate_locations |   | Table does not exist
wpms_9_woocommerce_shipping_zones |   | Table does not exist
wpms_9_woocommerce_shipping_zone_locations |   | Table does not exist
wpms_9_woocommerce_shipping_zone_methods |   | Table does not exist
wpms_9_woocommerce_payment_tokens |   | Table does not exist
wpms_9_woocommerce_payment_tokenmeta |   | Table does not exist
wpms_9_woocommerce_log |   | Table does not exist

So something is causing the template to not create all of the tables.  

Wordpress version 5.3.2
MySQL version 5.6.40
PHP version 7.2.26

**Comment by atif-kht** [comment]
Add the following snippet in a mu-plugin:

```
<?php
add_filter( 'nbt_copy_additional_tables', function( $source_tables ){
	$wc_table = 'wc_download_log';
	$values_to_push = array();

	foreach ( $source_tables as $key => $table ) {
		if ( substr_compare( $table, $wc_table, -strlen( $wc_table ) ) === 0 ) {
			unset( $source_tables[$key] );
			$values_to_push[] = $table;
		}
	}

	if( ! empty( $values_to_push ) ) {
		$source_tables = array_merge( $source_tables, $values_to_push );
	}
	return $source_tables;
}, 20 );

add_filter( 'nbt_create_additional_table_query' , function( $query, $new_table, $table ){
	$wc_table = 'wc_download_log';
	if ( substr_compare( $new_table, $wc_table, -strlen( $wc_table ) ) === 0 ) {
		$source_blog_id = str_replace( $wc_table, '', $table );
		$new_blog_id = str_replace( $wc_table, '', $new_table );
		$query = str_replace( $source_blog_id, $new_blog_id, $query );
	}
	return $query;
}, 20, 3 );

```

Actually, table `wc_download_log` has a CONSTRAINT which requires that another table (woocommerce_downloadable_product_permissions) exists already in DB in order for it to copy. And above code will make sure that it does before the later run.

**Comment by jeffro84** [comment]
That fixed it, thank you!
